#!/usr/bin/env python3
"""Native Python structural validator for the claude skill pack."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

SCRIPT = Path(__file__).absolute()
ENGINE_NAME = "skill_pack_validator_runtime.py"


def _load_validator_engine():
    candidates = [SCRIPT.parent / ENGINE_NAME]
    if len(SCRIPT.parents) > 3:
        source_root = SCRIPT.parents[3]
        expected_source = (
            source_root
            / "src.claude"
            / "agents"
            / "scripts"
            / SCRIPT.name
        )
        if SCRIPT == expected_source.resolve():
            candidates.append(source_root / "scripts" / ENGINE_NAME)
    for candidate in candidates:
        candidate = candidate.resolve()
        if not candidate.is_file():
            continue
        spec = importlib.util.spec_from_file_location(
            "_orchestrarium_skill_pack_validator_runtime",
            candidate,
        )
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    raise RuntimeError("validator-engine-not-found")


_ENGINE = _load_validator_engine()
validate_pack = _ENGINE.validate_pack
run_validator_cli = _ENGINE.run_validator_cli

PROVIDER = 'claude'
MAINTAINER_ONLY_SHARED_REFERENCE_NAMES = frozenset({"cross-pack-reconciliation.md"})
UTILITY_SKILLS = frozenset(
    {"init-project", "external-brigade", "second-opinion", "review-changes", "review-loop", "design-panel"}
)
CURATED_ROLE_SKILLS = frozenset({"lead", "product-manager", "analyst", "architect", "planner"})

_DECLARED_ACTIONS = (('direct', 'exists', 'src.claude/CLAUDE.md exists'),
 ('direct', 'exists', 'shared/AGENTS.shared.md exists'),
 ('direct', 'exists', 'src.claude/agents/lead.md exists'),
 ('direct', 'exists', 'src.claude/skills/lead/SKILL.md exists'),
 ('direct', 'exists', 'src.claude/agents/consultant.md exists'),
 ('direct', 'exists', 'src.claude/agents/external-worker.md exists'),
 ('direct', 'exists', 'src.claude/agents/external-reviewer.md exists'),
 ('direct', 'exists', 'src.claude/agents/scripts/invoke-claude-api.py exists'),
 ('direct', 'exists', 'src.claude/agents/scripts/invoke-claude-api.sh exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/operating-model.md exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/external-dispatch.md exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/subagent-contracts.md exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/policies-catalog.md exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/review-loop.md exists'),
 ('direct', 'exists', 'src.claude/agents/contracts/design-panel.md exists'),
 ('direct', 'exists', 'src.claude/commands/agents-external-brigade.md exists'),
 ('direct', 'exists', 'src.claude/commands/agents-second-opinion.md exists'),
 ('direct', 'exists', 'src.claude/commands/agents-review-loop.md exists'),
 ('direct', 'exists', 'src.claude/commands/agents-design-panel.md exists'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP1',
  'design-panel contract carries invariant marker DP1'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP2',
  'design-panel contract carries invariant marker DP2'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP3',
  'design-panel contract carries invariant marker DP3'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP4',
  'design-panel contract carries invariant marker DP4'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP5',
  'design-panel contract carries invariant marker DP5'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP6',
  'design-panel contract carries invariant marker DP6'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP7',
  'design-panel contract carries invariant marker DP7'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'DP8',
  'design-panel contract carries invariant marker DP8'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'INPUT_ONLY',
  'design-panel contract carries the INPUT_ONLY candidate disposition marker'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'RETURN(lead)',
  'design-panel contract carries the RETURN(lead) ledger-gate marker'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'synthesis',
  'design-panel contract names the synthesis step'),
 ('check_contains',
  'src.claude/agents/contracts/design-panel.md',
  'N >= 2',
  'design-panel contract carries the N >= 2 quorum marker'),
 ('check_contains',
  'src.claude/commands/agents-design-panel.md',
  'design-panel.md',
  'agents-design-panel command points at the installed contract'),
 ('check_contains',
  'src.claude/CLAUDE.md',
  'agents-design-panel.md',
  'CLAUDE.md dispatch index exposes the design-panel command'),
 ('check_contains',
  'src.claude/commands/agents-help.md',
  '/agents-design-panel',
  'agents-help lists the design-panel command'),
 ('check_contains',
  'src.claude/agents/contracts/operating-model.md',
  'Design-panel and review-loop selection',
  'operating-model carries the design-panel/review-loop selection block'),
 ('check_h2_section_contains',
  'src.claude/agents/contracts/operating-model.md',
  '## Design-panel and review-loop selection',
  'agents/contracts/design-panel.md',
  'operating-model design-panel selection block names the installed binding path'),
 ('check_h2_section_contains',
  'src.claude/agents/contracts/operating-model.md',
  '## Design-panel and review-loop selection',
  'independence at **generation**',
  'operating-model design-panel selection block states the generation side of the distinction'),
 ('check_h2_section_contains',
  'src.claude/agents/contracts/operating-model.md',
  '## Design-panel and review-loop selection',
  'independence at **verification**',
  'operating-model design-panel selection block states the verification side of the distinction'),
 ('check_contains',
  'src.claude/commands/agents-status.md',
  'Reserved PM admissions',
  'agents-status flags reserved product-manager admissions'),
 ('check_contains',
  'src.claude/commands/agents-status.md',
  'I will not dispatch or modify',
  'agents-status reserved-PM offer stays read-only (no dispatch/modify without confirmation)'),
 ('check_contains',
  'src.claude/skills/lead/SKILL.md',
  'hold the Lead role AS the main conversation',
  'lead skill declares the Lead role is held AS the main conversation'),
 ('check_absent',
  'src.claude/skills/lead/SKILL.md',
  'context: fork',
  'lead skill is not dispatched as a forked subagent (no context: fork)'),
 ('direct', 'exists', '@ROOT/shared/references/README.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/evidence-based-answer-pipeline.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/subagent-operating-model.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/workflow-strategy-comparison.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/repository-publication-safety.md exists'),
 ('direct', 'exists', '@ROOT/shared/schemas/agent-runs.schema.json exists'),
 ('direct', 'exists', '@ROOT/scripts/check-agent-run-ledger-contract.py exists'),
 ('direct', 'exists', '@ROOT/scripts/agent-run-ledger.py exists'),
 ('direct', 'exists', '@ROOT/scripts/agent-run-ledger.sh exists'),
 ('direct', 'exists', '@ROOT/scripts/check-work-items-state.py exists'),
 ('direct', 'exists', '@ROOT/scripts/check-work-items-state.sh exists'),
 ('direct', 'exists', '@ROOT/scripts/validate-work-item-state.py exists'),
 ('direct', 'exists', '@ROOT/scripts/validate-work-item-state.sh exists'),
 ('direct', 'exists', '@ROOT/shared/references/ru/subagent-operating-model.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/ru/workflow-strategy-comparison.md exists'),
 ('direct', 'exists', '@ROOT/shared/references/ru/repository-publication-safety.md exists'),
 ('check_pointer',
  '@ROOT/references-claude/evidence-based-answer-pipeline.md',
  '../shared/references/evidence-based-answer-pipeline.md'),
 ('check_pointer',
  '@ROOT/references-claude/subagent-operating-model.md',
  '../shared/references/subagent-operating-model.md'),
 ('check_pointer',
  '@ROOT/references-claude/workflow-strategy-comparison.md',
  '../shared/references/workflow-strategy-comparison.md'),
 ('check_pointer',
  '@ROOT/references-claude/repository-publication-safety.md',
  '../shared/references/repository-publication-safety.md'),
 ('check_pointer',
  '@ROOT/references-claude/ru/subagent-operating-model.md',
  '../../shared/references/ru/subagent-operating-model.md'),
 ('check_pointer',
  '@ROOT/references-claude/ru/workflow-strategy-comparison.md',
  '../../shared/references/ru/workflow-strategy-comparison.md'),
 ('check_pointer',
  '@ROOT/references-claude/ru/repository-publication-safety.md',
  '../../shared/references/ru/repository-publication-safety.md'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  "This file is the canonical shared core for the repository's subagent operating model.",
  'shared subagent-operating-model declares canonical shared-core ownership'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Keep runtime-specific paths, provider dispatch details, execution-model differences, and repository '
  'concretization in the corresponding pack-local addendum.',
  'shared subagent-operating-model keeps runtime specifics in pack-local addenda'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'and any pack-local provider-specific fields',
  'shared subagent-operating-model allows provider-specific addendum fields'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'A subagent `PASS`, report, or claimed test result is a claim, not proof',
  'shared subagent-operating-model requires subagent result verification'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Visual artifact verification amendment',
  'shared subagent-operating-model requires visual artifact inspection'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Documentation terminology amendment',
  'shared subagent-operating-model documents terminology glossary discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Markdown formula rendering amendment',
  'shared subagent-operating-model documents Markdown formula rendering discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'split long derivations into several short one-line',
  'shared subagent-operating-model preserves fragile previewer formula fallback'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'do not use multi-line `$$...$$` display blocks',
  'shared subagent-operating-model rejects unverified multi-line display math'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'compatibility hacks such as `\\sb` or `\\sp`',
  'shared subagent-operating-model forbids formula compatibility hacks'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'unbalanced dollar delimiters',
  'shared subagent-operating-model scans for delimiter and table breakage'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Formula scope and assumptions amendment',
  'shared subagent-operating-model documents formula scope discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'tool availability',
  'shared subagent-operating-model preserves canonical-source ambiguity inspection'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'smallest safe reversible subset',
  'shared subagent-operating-model preserves user-intent fallback discipline'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '.agents/.agents-mode.yaml',
  'shared subagent-operating-model stays free of Codex-specific agents-mode paths'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '.claude/.agents-mode.yaml',
  'shared subagent-operating-model stays free of Claude-specific agents-mode paths'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'work-items/index.md',
  'shared subagent-operating-model stays free of Claude task-memory concretization'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'externalClaudeProfile',
  'shared subagent-operating-model stays free of provider-specific profile fields'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Claude CLI',
  'shared subagent-operating-model stays free of provider-specific dispatch destinations'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Codex CLI',
  'shared subagent-operating-model stays free of provider-specific dispatch origins'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'shared subagent-operating-model stays free of Codex addendum sections'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'shared subagent-operating-model stays free of Claude addendum sections'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 1. Main rule for the lead',
  'shared subagent-operating-model keeps the main-rule section in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 6. Role map',
  'shared subagent-operating-model keeps the role-map section in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 8. Gates: what each stage must prove',
  'shared subagent-operating-model keeps the gate model in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'agent-runs.jsonl` is the machine-readable execution ledger',
  'shared subagent-operating-model documents the agent execution ledger'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'no accepted `PASS` without evidence',
  'shared subagent-operating-model rejects PASS without evidence'),
 ('check_h2_section_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 3.10 Periodic controls',
  'Use the corresponding pack-local `periodic-control-matrix.md` named in the local addendum as the '
  'canonical cadence, owner, evidence, and fail-action matrix.',
  'shared periodic-controls section routes ownership back through the pack-local addendum'),
 ('check_h2_section_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 3.10 Periodic controls',
  '[periodic-control-matrix.md](periodic-control-matrix.md)',
  'shared periodic-controls section does not keep a broken shared periodic-control link'),
 ('check_exact_h2_inventory',
  '@ROOT/shared/references/subagent-operating-model.md',
  'shared subagent-operating-model keeps the canonical shared-core H2 skeleton',
  '## 1. Main rule for the lead',
  '## 2. What this means in practice',
  '## 3. Team operating model',
  '## 3.10 Periodic controls',
  '## 4. Standard task template for any subagent',
  '## 5. Shared system preamble for all subagents',
  '## 6. Role map',
  '## 7. Ready-made role prompts',
  '## 8. Gates: what each stage must prove',
  '## 9. Practical routing patterns',
  '## 10. Rules for parallel work',
  '## 11. Governance notes',
  '## 12. Team composition',
  '## 13. Short memo for the lead',
  '## 14. Final wording to give the lead',
  '## Terms and Abbreviations'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'Consultant config lives in `.claude/.agents-mode.yaml`',
  'Claude runtime-notes section documents the Claude agents-mode path'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'does not include `externalClaudeProfile`',
  'Claude runtime-notes section documents that externalClaudeProfile is not canonical on the Claude line'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'shipped production `auto` uses `codex | claude` only',
  'Claude runtime-notes section documents profile-based Claude external dispatch'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-side repository concretization',
  'generated `work-items/README.md`',
  'Claude repository-concretization section points human recovery at the generated README read-model'),
 ('check_h2_section_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  '.agents/.agents-mode.yaml',
  'Claude runtime-notes section does not accidentally carry Codex agents-mode paths'),
 ('check_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'Claude addendum keeps the Claude runtime-notes section'),
 ('check_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-side repository concretization',
  'Claude addendum keeps the Claude repository-concretization section'),
 ('check_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Shared core now owns',
  'Claude addendum keeps the shared-core ownership handoff section'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Claude-side repository concretization',
  '[periodic-control-matrix.md](periodic-control-matrix.md)',
  'Claude repository-concretization section keeps the pack-local periodic-control reference'),
 ('check_h2_section_contains',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## Shared core now owns',
  'Main rule, core management rules, delivery loops, routing patterns, role map, prompts, gates, and team '
  'composition',
  'Claude shared-core handoff section states which methodology stays in the shared core'),
 ('check_exact_h2_inventory',
  '@ROOT/references-claude/subagent-operating-model.md',
  'Claude addendum keeps the exact addendum-only H2 skeleton',
  '## Claude-specific runtime notes',
  '## Claude-side repository concretization',
  '## Shared core now owns'),
 ('check_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## 1. Main rule for the lead',
  'Claude addendum does not reintroduce the shared main-rule section'),
 ('check_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## 6. Role map',
  'Claude addendum does not reintroduce the shared role-map section'),
 ('check_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## 8. Gates: what each stage must prove',
  'Claude addendum does not reintroduce the shared gate section'),
 ('check_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## 9. Practical routing patterns',
  'Claude addendum does not reintroduce the shared routing-patterns section'),
 ('check_absent',
  '@ROOT/references-claude/subagent-operating-model.md',
  '## 12. Team composition',
  'Claude addendum does not reintroduce the shared team-composition section'),
 ('check_max_lines',
  '@ROOT/references-claude/subagent-operating-model.md',
  '120',
  'Claude addendum stays bounded instead of regrowing into a full blueprint copy'),
 ('check_normalized_sha256',
  '@ROOT/shared/references/subagent-operating-model.md',
  'fa464ae90e0c66a22fdf6dfbe875ab3db7815b4aa9db2d0b75df0dc92318f864',
  'shared subagent-operating-model matches the current canonical normalized fingerprint'),
 ('check_normalized_sha256',
  '@ROOT/references-claude/subagent-operating-model.md',
  '9e1db8ab1837ff63faa34b5df042f736f679912a40ff6f57608ec257033278c6',
  'Claude addendum matches the current canonical normalized fingerprint'),
 ('direct', 'role_index_claude', 'role_index_claude'),
 ('check_common_skill_body_pin',
  'analyzing-video-bugs',
  'cf78ec0176f1726891045a2c2626363377994f34f081f9a9ad0ffbdb60740e91',
  'src.claude/skills/analyzing-video-bugs/SKILL.md'),
 ('check_common_skill_body_pin',
  'bug-hunting',
  '56c6ed8a5a590559bdf29409102b2b8b654bf73c7be2b4ef23c4d2c74e019232',
  'src.claude/skills/bug-hunting/SKILL.md'),
 ('check_common_skill_body_pin',
  'explain-simply',
  'f0f0e4dd1bed68aa8114adf6059fea32fedbee8fd06bf8bb12042dcd07ebb408',
  'src.claude/skills/explain-simply/SKILL.md'),
 ('check_common_skill_body_pin',
  'mathtype-book-page',
  '615499de68dc03fccb23954e8ed94662076a9a744a493b71232ebdcce55357be',
  'src.claude/skills/mathtype-book-page/SKILL.md'),
 ('check_common_skill_body_pin',
  'vak-dissertation-review',
  'e259d114a1ea2372d9152a07445aeba82c51493b9caf7b39f3b6b96678e9b261',
  'src.claude/skills/vak-dissertation-review/SKILL.md'),
 ('check_common_skill_body_pin',
  'windows-gui-manual-testing',
  'b3a029e6784d1d9e37f789b8b512f31f5e5c2161ca6807dc8a140854042ae6c8',
  'src.claude/skills/windows-gui-manual-testing/SKILL.md'),
 ('direct', 'common_pin_completeness', 'common_pin_completeness'),
 ('check_file', 'src.claude/skills/lead/SKILL.md', 'lead has a curated role-skill file'),
 ('check_file',
  'src.claude/skills/product-manager/SKILL.md',
  'product-manager has a curated role-skill file'),
 ('check_file', 'src.claude/skills/analyst/SKILL.md', 'analyst has a curated role-skill file'),
 ('check_file', 'src.claude/skills/architect/SKILL.md', 'architect has a curated role-skill file'),
 ('check_file', 'src.claude/skills/planner/SKILL.md', 'planner has a curated role-skill file'),
 ('check_contains',
  'src.claude/agents/product-manager.md',
  'invoke the `Skill` tool with name `product-manager` to load the full role contract',
  'product-manager agent wrapper pins to its curated skill via the Skill tool'),
 ('check_absent',
  'src.claude/agents/product-manager.md',
  'lead-is-a-main-conversation-role',
  'product-manager agent wrapper is not a fail-closed stub (dual role must stay a valid dispatch target)'),
 ('check_contains',
  'src.claude/agents/analyst.md',
  'invoke the `Skill` tool with name `analyst` to load the full role contract',
  'analyst agent wrapper pins to its curated skill via the Skill tool'),
 ('check_absent',
  'src.claude/agents/analyst.md',
  'lead-is-a-main-conversation-role',
  'analyst agent wrapper is not a fail-closed stub (dual role must stay a valid dispatch target)'),
 ('check_contains',
  'src.claude/agents/architect.md',
  'invoke the `Skill` tool with name `architect` to load the full role contract',
  'architect agent wrapper pins to its curated skill via the Skill tool'),
 ('check_absent',
  'src.claude/agents/architect.md',
  'lead-is-a-main-conversation-role',
  'architect agent wrapper is not a fail-closed stub (dual role must stay a valid dispatch target)'),
 ('check_contains',
  'src.claude/agents/planner.md',
  'invoke the `Skill` tool with name `planner` to load the full role contract',
  'planner agent wrapper pins to its curated skill via the Skill tool'),
 ('check_absent',
  'src.claude/agents/planner.md',
  'lead-is-a-main-conversation-role',
  'planner agent wrapper is not a fail-closed stub (dual role must stay a valid dispatch target)'),
 ('direct', 'curated_registry', 'curated_registry'),
 ('direct', 'layering_claude', 'layering_claude'),
 ('direct', 'team_templates', 'team_templates'),
 ('direct', 'command_prefixes', 'command_prefixes'),
 ('direct', 'skill_frontmatter', 'skill_frontmatter'),
 ('direct', 'policy_catalog', 'policy catalog exists'),
 ('direct', 'scripts_claude', 'scripts_claude'),
 ('direct', 'claude_heading', '## Delegation rule present in CLAUDE.md'),
 ('direct', 'agents_heading', '## Role index present in AGENTS.md'),
 ('direct', 'agents_heading', '## Engineering hygiene present in AGENTS.md'),
 ('direct', 'agents_heading', '## Publication safety present in AGENTS.md'),
 ('direct', 'agents_heading', '## Core delegation principles present in AGENTS.md'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'consultantMode: auto',
  'consultant doc does not document consultantMode auto'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'fallback approved by user',
  'consultant doc does not reserve consultant fallback deviations'),
 ('check_absent',
  'src.claude/commands/agents-second-opinion.md',
  'consultantMode: auto',
  'agents-second-opinion command does not expose consultantMode auto'),
 ('check_absent',
  'src.claude/commands/agents-init-project.md',
  'allowed: external | auto | internal | disabled',
  'agents-init-project restricts consultantMode to external/internal/disabled'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'allowed: external | auto | internal | disabled',
  'external-dispatch schema restricts consultantMode to external/internal/disabled'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'fallback approved by user',
  'external-dispatch does not record consultant fallback approvals'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'Read and normalize `.claude/.agents-mode.yaml` first.',
  'subagent-contracts require read-time agents-mode normalization'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'agent-runs.jsonl format',
  'subagent-contracts define the agent run ledger format'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'A `PASS` in `status.md` is not accepted',
  'subagent-contracts reject PASS without ledger evidence'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'shared/schemas/agent-runs.schema.json',
  'subagent-contracts point to the shared ledger schema'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'scripts/agent-run-ledger.*',
  'subagent-contracts point to the work-item ledger helper'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'scripts/validate-work-item-state.* --work-item',
  'subagent-contracts point to the work-item state validator'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  'scripts/check-work-items-state.* --root',
  'subagent-contracts point to the periodic work-item state checker'),
 ('check_contains',
  'src.claude/commands/agents-bugfix.md',
  '**Second-cross-break stop:** If a second fix in the same session breaks a previously working neighbor, '
  'STOP all edits.',
  'agents-bugfix carries the P4 second-cross-break stop rule'),
 ('check_contains',
  'src.claude/agents/hooks/check-no-trash-in-repo.py',
  'REQUESTED_ISOLATION_MARKER = "# orchestrarium:requested-isolation-worktree"',
  'no-trash-in-repo hook carries the A2 requested-isolation-worktree marker constant'),
 ('check_contains',
  'src.claude/agents/contracts/review-loop.md',
  '**Failed lane is unverified.** Any expected lane that errors, dies, or hits a time/token/usage limit is '
  'UNVERIFIED.',
  'review-loop contract carries the A5b failed-lane-is-unverified invariant'),
 ('check_contains',
  'src.claude/agents/contracts/review-loop.md',
  '**Fail-closed aggregation.** A missing/null sub-verdict or findings payload is NOT-clean.',
  'review-loop contract carries the A5b fail-closed-aggregation invariant'),
 ('check_contains',
  'src.claude/agents/contracts/subagent-contracts.md',
  '**Class-completeness trigger (mandatory):** when a reviewer, bot, or test cites one instance of a defect '
  'class',
  'subagent-contracts carry the A8 class-completeness trigger'),
 ('check_contains',
  'src.claude/agents/contracts/external-dispatch.md',
  'Every provider-backed run MUST carry the resolved model/profile and effort as explicit launch flags in '
  'that invocation, even when they equal configured defaults; never rely on provider config defaults.',
  'external-dispatch carries the A12 explicit model/effort launch rule'),
 ('check_contains',
  'src.claude/agents/contracts/operating-model.md',
  'lifecycle state change (create, resume, stage transition, park, close, archive)',
  'operating-model carries the A3 physical-state reconciliation trigger'),
 ('check_contains',
  'src.claude/commands/agents-init-project.md',
  'normalize it to the current canonical format before presenting or trusting the current values.',
  'agents-init-project normalizes existing agents-mode before reading values'),
 ('check_contains',
  'src.claude/commands/agents-init-project.md',
  'Any read of `.claude/.agents-mode.yaml` that drives a decision should normalize the file to the current '
  'canonical format before trusting the flags.',
  'agents-init-project requires read-time agents-mode normalization'),
 ('check_contains',
  'src.claude/commands/agents-second-opinion.md',
  'read and normalize `.claude/.agents-mode.yaml`.',
  'agents-second-opinion normalizes agents-mode before reporting status'),
 ('check_absent',
  'shared/AGENTS.shared.md',
  'Adapter host runtime',
  'shared governance no longer allows adapter-host metadata for external execution'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'must use direct external launch',
  'shared governance requires direct external launch'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'substantive task prompt must use file-based prompt delivery',
  'shared governance requires file-based external CLI prompts'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'Mechanism inventory before new paths',
  'shared governance requires owner inventory before new mechanisms'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'State-synchronization ownership',
  'shared governance requires state synchronization ownership discipline'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'split-brain state sync as an architecture bug',
  'shared governance rejects split-brain state synchronization'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'correlation IDs',
  'shared governance requires traceable state synchronization diagnostics'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'Read and normalize `.claude/.agents-mode.yaml` to the current canonical format before trusting its flags.',
  'external-worker normalizes agents-mode before routing'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'Read and normalize `.claude/.agents-mode.yaml` to the current canonical format before trusting its flags.',
  'external-reviewer normalizes agents-mode before routing'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'Adapter host runtime:',
  'external-dispatch no longer records adapter host runtime'),
 ('check_contains',
  'src.claude/agents/contracts/external-dispatch.md',
  'must use direct external launch',
  'external-dispatch requires direct external launch'),
 ('check_contains',
  'src.claude/agents/contracts/external-dispatch.md',
  'substantive task prompt must use file-based prompt delivery',
  'external-dispatch requires file-based external CLI prompts'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'verify every subagent result before accepting it',
  'shared governance requires verification before trusting subagent results'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'Visual artifact verification discipline',
  'shared governance requires visual inspection for generated visual artifacts'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'Plain-language and terminology discipline',
  'shared governance requires terminology and abbreviation explanations in documents'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'concrete observable data',
  'shared governance requires measured evidence before root-cause or fix claims'),
 ('check_contains',
  'shared/AGENTS.shared.md',
  'smallest safe reversible subset',
  'shared governance preserves user-intent fallback discipline'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'Adapter host runtime:',
  'consultant no longer records adapter host runtime'),
 ('check_contains',
  'src.claude/agents/consultant.md',
  'must use direct external launch',
  'consultant requires direct external launch when external'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'Requested provider: <auto',
  'consultant provenance no longer emits auto as a requested provider'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'Requested provider: <auto',
  'external-dispatch provenance no longer emits auto as a requested provider'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'Actual execution path:** <external CLI (provider name) | internal subagent',
  'consultant does not mislabel internal subagent as actual execution path'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'externalPriorityProfile',
  'external-worker honors structured profile keys'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'externalPriorityProfile',
  'external-reviewer honors structured profile keys'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'direct external launch contract',
  'external-worker requires direct external launch'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'file-based prompt delivery',
  'external-worker requires file-based external CLI prompts'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'direct external launch contract',
  'external-reviewer requires direct external launch'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'file-based prompt delivery',
  'external-reviewer requires file-based external CLI prompts'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.sh',
  'invoke-claude-api.py',
  'Bash Claude API launcher delegates to the Python owner'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.py',
  'SECRET.md',
  'Python Claude API entrypoint reads SECRET.md'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.py',
  'resolve_claude_command',
  'Python Claude secret-backed entrypoint resolves plain claude'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.py',
  '--print-secret-path',
  'Python Claude API entrypoint supports print-secret-path'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.py',
  'CLAUDE_BIN',
  'Python Claude secret-backed entrypoint documents CLAUDE_BIN override'),
 ('check_contains',
  'src.claude/agents/scripts/invoke-claude-api.py',
  'claude.cmd',
  'Python Claude secret-backed entrypoint resolves Windows claude.cmd'),
 ('check_contains',
  'src.claude/agents/contracts/external-dispatch.md',
  'one instance per helper or provider',
  'external-dispatch documents same-provider brigade reuse'),
 ('check_contains',
  'src.claude/commands/agents-external-brigade.md',
  'same-provider helper instances',
  'agents-external-brigade command documents same-provider helper fan-out'),
 ('check_contains',
  'src.claude/commands/agents-help.md',
  '/agents-external-brigade',
  'agents-help lists the external-brigade command'),
 ('check_contains',
  'src.claude/agents/lead.md',
  '/agents-external-brigade',
  'lead guide mentions the external-brigade command'),
 ('check_absent',
  'src.claude/CLAUDE.md',
  'gemini-crosscheck',
  'src.claude/CLAUDE.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/CLAUDE.md',
  'externalGeminiFallbackMode',
  'src.claude/CLAUDE.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/CLAUDE.md',
  'externalGeminiWorkdirMode',
  'src.claude/CLAUDE.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'gemini-crosscheck',
  'src.claude/agents/contracts/external-dispatch.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/contracts/external-dispatch.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/contracts/external-dispatch.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/contracts/external-dispatch.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/contracts/operating-model.md',
  'gemini-crosscheck',
  'src.claude/agents/contracts/operating-model.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/contracts/operating-model.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/contracts/operating-model.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/contracts/operating-model.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/contracts/operating-model.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/contracts/subagent-contracts.md',
  'gemini-crosscheck',
  'src.claude/agents/contracts/subagent-contracts.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/contracts/subagent-contracts.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/contracts/subagent-contracts.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/contracts/subagent-contracts.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/contracts/subagent-contracts.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'gemini-crosscheck',
  'src.claude/agents/consultant.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/consultant.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/consultant.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/consultant.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/external-worker.md',
  'gemini-crosscheck',
  'src.claude/agents/external-worker.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/external-worker.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/external-worker.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/external-worker.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/external-worker.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/external-reviewer.md',
  'gemini-crosscheck',
  'src.claude/agents/external-reviewer.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/external-reviewer.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/external-reviewer.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/external-reviewer.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/external-reviewer.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/graphics-engineer.md',
  'gemini-crosscheck',
  'src.claude/agents/graphics-engineer.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/graphics-engineer.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/graphics-engineer.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/graphics-engineer.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/graphics-engineer.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/agents/visualization-engineer.md',
  'gemini-crosscheck',
  'src.claude/agents/visualization-engineer.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/agents/visualization-engineer.md',
  'externalGeminiFallbackMode',
  'src.claude/agents/visualization-engineer.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/agents/visualization-engineer.md',
  'externalGeminiWorkdirMode',
  'src.claude/agents/visualization-engineer.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/commands/agents-help.md',
  'gemini-crosscheck',
  'src.claude/commands/agents-help.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/commands/agents-help.md',
  'externalGeminiFallbackMode',
  'src.claude/commands/agents-help.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/commands/agents-help.md',
  'externalGeminiWorkdirMode',
  'src.claude/commands/agents-help.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/commands/agents-init-project.md',
  'gemini-crosscheck',
  'src.claude/commands/agents-init-project.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/commands/agents-init-project.md',
  'externalGeminiFallbackMode',
  'src.claude/commands/agents-init-project.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/commands/agents-init-project.md',
  'externalGeminiWorkdirMode',
  'src.claude/commands/agents-init-project.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/commands/agents-second-opinion.md',
  'gemini-crosscheck',
  'src.claude/commands/agents-second-opinion.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/commands/agents-second-opinion.md',
  'externalGeminiFallbackMode',
  'src.claude/commands/agents-second-opinion.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/commands/agents-second-opinion.md',
  'externalGeminiWorkdirMode',
  'src.claude/commands/agents-second-opinion.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  'src.claude/commands/agents-external-brigade.md',
  'gemini-crosscheck',
  'src.claude/commands/agents-external-brigade.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  'src.claude/commands/agents-external-brigade.md',
  'externalGeminiFallbackMode',
  'src.claude/commands/agents-external-brigade.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  'src.claude/commands/agents-external-brigade.md',
  'externalGeminiWorkdirMode',
  'src.claude/commands/agents-external-brigade.md removes retired externalGeminiWorkdirMode'),
 ('check_contains',
  'src.claude/CLAUDE.md',
  'auto | codex | claude | gemini | qwen',
  'Claude pack docs document the example-only Gemini/Qwen provider universe'),
 ('check_contains',
  'src.claude/CLAUDE.md',
  'Gemini and Qwen are `WEAK MODEL / NOT RECOMMENDED`',
  'Claude entrypoint marks Gemini/Qwen as not recommended example routes'),
 ('check_contains',
  'src.claude/CLAUDE.md',
  'never a provider entry inside `externalPriorityProfiles`',
  'Claude entrypoint forbids Gemini/Qwen profile entries'),
 ('check_contains',
  'src.claude/agents/consultant.md',
  'Gemini and Qwen stay explicit `WEAK MODEL / NOT RECOMMENDED` example-only paths',
  'Claude consultant marks Gemini/Qwen as not recommended example routes'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'manual `WEAK MODEL / NOT RECOMMENDED` example-only paths',
  'Claude external-worker marks Gemini/Qwen as not recommended example routes'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'manual `WEAK MODEL / NOT RECOMMENDED` example-only paths',
  'Claude external-reviewer marks Gemini/Qwen as not recommended example routes'),
 ('check_contains',
  'src.claude/agents/external-worker.md',
  'instead of broadening shipped or repo-local `auto` profiles',
  'Claude external-worker forbids example-provider profile broadening'),
 ('check_contains',
  'src.claude/agents/external-reviewer.md',
  'instead of broadening shipped or repo-local `auto` profiles',
  'Claude external-reviewer forbids example-provider profile broadening'),
 ('check_contains',
  'src.claude/agents/contracts/operating-model.md',
  'Gemini and Qwen stay explicit `WEAK MODEL / NOT RECOMMENDED` example-only paths',
  'Claude operating-model marks Gemini/Qwen as not recommended example routes'),
 ('check_contains',
  '@ROOT/shared/references/README.md',
  'deprecated Gemini and Qwen full-mirror examples',
  'shared reference index marks Gemini/Qwen full mirrors deprecated'),
 ('check_contains',
  '@ROOT/src.gemini/README.md',
  '**DEPRECATED:** this full-mirror Gemini pack',
  'Gemini pack README marks the current full-mirror form deprecated'),
 ('check_contains',
  '@ROOT/src.qwen/README.md',
  '**DEPRECATED:** this full-mirror Qwen pack',
  'Qwen pack README marks the current full-mirror form deprecated'),
 ('check_contains',
  '@ROOT/install.sh',
  '"$SCRIPT_DIR/install.py"',
  'root Bash launcher delegates to the Python owner'),
 ('check_contains',
  '@ROOT/install.py',
  'default production install',
  'root Python installer defaults to the Codex/Claude production pair'),
 ('check_contains',
  '@ROOT/install.py',
  'DEPRECATED / WEAK MODEL / NOT RECOMMENDED',
  'root Python installer labels Gemini/Qwen choices deprecated'),
 ('check_absent',
  '@ROOT/install.py',
  'All available root installs',
  'root Python installer does not offer all-provider default installs'),
 ('check_contains',
  '@ROOT/install.py',
  '.strip() or "3"',
  'root Python installer maps empty selection to option 3'),
 ('direct', 'installer_default', 'root Python installer default dispatch is Codex plus Claude only'),
 ('check_absent',
  '@ROOT/install.py',
  'run_all_available',
  'root Python installer has no aggregate all-provider helper'),
 ('check_contains',
  '@ROOT/README.md',
  'Pressing Enter selects the default production install',
  'README documents the Codex/Claude default root install'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'Pressing Enter selects the default production install',
  'INSTALL.md documents the Codex/Claude default root install'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  '.agents-mode.yaml',
  'INSTALL.md default project result includes provider overlay files'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  '`power-mode` | hardest-task maximum result',
  'agents-mode reference documents power-mode preset'),
 ('check_contains',
  '@ROOT/src.claude/commands/agents-init-project.md',
  '`power-mode` (hardest-task maximum result)',
  'Claude init-project exposes power-mode preset'),
 ('check_contains',
  '@ROOT/src.claude/commands/agents-init-project.md',
  'review.security: 2',
  'Claude init-project correctness-first/power-mode presets raise review.security'),
 ('check_contains',
  '@ROOT/src.claude/commands/agents-init-project.md',
  'review.ui-visual-correctness: 2',
  'Claude init-project correctness-first/power-mode presets raise review.ui-visual-correctness'),
 ('direct', 'agents_contract', 'agents-mode machine-readable contract matches docs and init preset surfaces'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  '## Canonical maintenance',
  'agents-mode reference defines canonical maintenance'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'Read-time normalization preserves the effective values of known keys',
  'agents-mode reference documents read-time normalization semantics'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'removes example-only providers from every `externalPriorityProfiles` provider list',
  'agents-mode reference documents profile provider sanitization'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'Substantive task prompts are file-based by default',
  'agents-mode reference documents file-based external CLI prompts'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'agent-runs.jsonl',
  'agents-mode reference documents ledger fan-out tracking'),
 ('check_contains',
  '@ROOT/docs/external-worker-design.md',
  'Work-item ledger rule',
  'external-worker design maps execution records to the ledger'),
 ('check_normalizer_strips_example_auto_providers',
  'agents-mode normalizer strips Gemini/Qwen and keeps reserve last or absent in custom auto profiles'),
 ('check_file', '@ROOT/shared/agents-mode.defaults.yaml', 'shared/agents-mode.defaults.yaml'),
 ('check_shared_defaults_reserve_policy', 'shared agents-mode defaults keep reserve advisory/review-only'),
 ('check_not_exists',
  '@ROOT/src.claude/agents-mode.defaults.yaml',
  'src.claude/agents-mode.defaults.yaml removed from the monorepo'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/validate-work-item-state.* --work-item',
  'README documents the work-item state validator'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/agent-run-ledger.* --work-item',
  'README documents the work-item ledger helper'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/check-work-items-state.* --root',
  'README documents the periodic work-item state checker'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'agent-runs.jsonl',
  'INSTALL documents local work-item execution tracking'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'scripts/agent-run-ledger.* --work-item',
  'INSTALL documents the work-item ledger helper'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'scripts/check-work-items-state.* --root',
  'INSTALL documents the periodic work-item state checker'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'machine-readable work-item execution tracking contract',
  'release notes document the work-item execution tracking contract'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'ledger append/init helper',
  'release notes document the ledger append/init helper'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'periodic active work-item state checker',
  'release notes document the periodic work-item checker'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.py',
  'validate_work_item',
  'agent-run-ledger helper reuses the work-item state validator'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.py',
  'restore_ledger',
  'agent-run-ledger helper rolls back invalid appends'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.sh',
  'agent-run-ledger.py',
  'agent-run-ledger Bash wrapper targets the Python helper'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.py',
  'validate_work_item',
  'periodic work-item checker reuses the work-item state validator'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.py',
  'stale running agent',
  'periodic work-item checker reports stale running agents'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.sh',
  'check-work-items-state.py',
  'periodic work-item Bash wrapper targets the Python checker'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'PASS gate requires evidence',
  'work-item state validator enforces evidence for PASS'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'escapes the work item',
  'work-item state validator confines PASS artifacts to the work item'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'agent-runs.jsonl',
  'work-item state validator loads the agent run ledger'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.sh',
  'validate-work-item-state.py',
  'work-item state Bash wrapper targets the Python validator'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  'agent-runs.schema.json',
  'agent run ledger schema has a stable id'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  '"executionRole"',
  'agent run ledger schema defines executionRole'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  '"evidence"',
  'agent run ledger schema defines evidence'),
 ('check_agent_run_ledger_contract', 'agent run ledger schema and validator reject schema-invalid events'),
 ('check_arch_layering_slices',
  'architecture-layering slices consistent across roles and claude/codex packs'),
 ('check_contains',
  '@AGENTS',
  "clarification that changes a live textual artifact's meaning supersedes its prior wording",
  'shared governance replaces meaning-changing textual clarifications instead of layering prose'))

_INSTALLED_ACTIONS = (
    (
        "check_normalized_sha256",
        "@PACK/contracts/ui-transition-continuity.md",
        "92af857398c6c56ff681fa91360673d7a9c2365f48734f6d83fa74d98e12cf62",
        "UI-CONTINUITY-CONTRACT-DRIFT: installed neutral contract leaf matches the canonical English fingerprint",
    ),
    ("check_file", "@SCRIPTS/agent-run-ledger.py", "installed agent-run-ledger.py"),
    ("check_file", "@SCRIPTS/agent-run-ledger.sh", "installed agent-run-ledger.sh"),
    ("check_file", "@SCRIPTS/review_loop_state.py", "installed review-loop state engine"),
    (
        "check_file",
        "@SCRIPTS/check-work-items-state.py",
        "installed check-work-items-state.py",
    ),
    (
        "check_file",
        "@SCRIPTS/check-work-items-state.sh",
        "installed check-work-items-state.sh",
    ),
    (
        "check_file",
        "@SCRIPTS/validate-work-item-state.py",
        "installed validate-work-item-state.py",
    ),
    (
        "check_file",
        "@SCRIPTS/validate-work-item-state.sh",
        "installed validate-work-item-state.sh",
    ),
    (
        "check_contains",
        "@SCRIPTS/agent-run-ledger.py",
        "validate_work_item",
        "installed agent-run-ledger helper reuses the validator",
    ),
    (
        "check_contains",
        "@SCRIPTS/check-work-items-state.py",
        "stale running agent",
        "installed periodic work-item checker reports stale running agents",
    ),
    (
        "check_contains",
        "@SCRIPTS/validate-work-item-state.py",
        "PASS gate requires evidence",
        "installed work-item state validator enforces evidence for PASS",
    ),
)

_APAT_ACTIONS = (
    ("check_file", "@PACK/skills/lead/SKILL.md", "APAT-E006-INSTALLED-MISSING: claude lead APAT projection file"),
    ("check_file", "@PACK/skills/architect/SKILL.md", "APAT-E006-INSTALLED-MISSING: claude architect AP0-AP5 projection file"),
    ("check_file", "@PACK/agents/architecture-reviewer.md", "APAT-E006-INSTALLED-MISSING: claude architecture-reviewer APAT projection file"),
    ("check_contains", "@PACK/skills/lead/SKILL.md", "<!-- APAT-BLOCK:LEAD-ROUTING:BEGIN -->", "APAT-E006-INSTALLED-MISSING: claude lead APAT-G04-PROVIDER-PARITY projection marker"),
    ("check_contains", "@PACK/skills/lead/SKILL.md", "is not a universal Architect prelude", "APAT-E006-INSTALLED-MISSING: claude lead APAT-G05-INSTALLED-PARITY negative-selection wording"),
    *(("check_contains", "@PACK/skills/architect/SKILL.md", f'<!-- APAT-SEMANTIC id="AP{number}.', f"APAT-E006-INSTALLED-MISSING: claude architect AP{number} marker") for number in range(6)),
    ("check_contains", "@PACK/skills/architect/SKILL.md", "<!-- APAT-BLOCK:ARCHITECT-DISPOSITION:BEGIN -->", "APAT-E006-INSTALLED-MISSING: claude architect AP0-AP5 projection section marker"),
    ("check_contains", "@PACK/agents/architecture-reviewer.md", "<!-- APAT-BLOCK:ARCHITECTURE-REVIEW:BEGIN -->", "APAT-E006-INSTALLED-MISSING: claude architecture-reviewer APAT projection section marker"),
    ("check_contains", "@PACK/agents/architecture-reviewer.md", "each tempting but unsuitable pattern has explicit negative evidence", "APAT-E006-INSTALLED-MISSING: claude architecture-reviewer APAT negative-selection wording"),
)

_APAT_DEV_ACTIONS = (
    ("check_file", "@ROOT/shared/references/architecture-pattern-applicability.md", "APAT-G04-PROVIDER-PARITY canonical applicability reference"),
    ("check_file", "@ROOT/shared/references/ru/architecture-pattern-applicability.md", "APAT-G04-PROVIDER-PARITY Russian applicability reference"),
)

_UI_CONTINUITY_DEV_ACTIONS = (
    (
        "check_normalized_sha256",
        "@ROOT/shared/references/ui-transition-continuity.md",
        "92af857398c6c56ff681fa91360673d7a9c2365f48734f6d83fa74d98e12cf62",
        "UI-CONTINUITY-CONTRACT-DRIFT: canonical English contract matches its declared fingerprint",
    ),
    (
        "check_contains",
        "@ROOT/scripts/production_installer.py",
        "UI_CONTINUITY_CONTRACT_SOURCE",
        "UI-CONTINUITY-CONTRACT-DRIFT: production installer declares the canonical contract source",
    ),
    (
        "check_contains",
        "@ROOT/scripts/production_installer.py",
        "UI_CONTINUITY_CONTRACT_TARGET",
        "UI-CONTINUITY-CONTRACT-DRIFT: production installer declares the neutral contract target",
    ),
    (
        "check_not_exists",
        "@ROOT/src.codex/contracts",
        "UI-CONTINUITY-CONTRACT-DRIFT: Codex has no provider-local contract copy",
    ),
    (
        "check_not_exists",
        "@ROOT/src.claude/contracts",
        "UI-CONTINUITY-CONTRACT-DRIFT: Claude has no provider-local contract copy",
    ),
)

ACTIONS = (
    ("all", _DECLARED_ACTIONS[0:42] + _DECLARED_ACTIONS[114:256] + _DECLARED_ACTIONS[308:309] + _APAT_ACTIONS),
    (
        "dev_repo",
        _DECLARED_ACTIONS[42:114]
        + _DECLARED_ACTIONS[269:273]
        + _DECLARED_ACTIONS[274:279]
        + _DECLARED_ACTIONS[280:284]
        + _DECLARED_ACTIONS[293:308]
        + _APAT_DEV_ACTIONS
        + _UI_CONTINUITY_DEV_ACTIONS,
    ),
    (
        "dev_repo_nonstandalone",
        _DECLARED_ACTIONS[256:269]
        + _DECLARED_ACTIONS[273:274]
        + _DECLARED_ACTIONS[279:280]
        + _DECLARED_ACTIONS[284:293],
    ),
    ("installed", _INSTALLED_ACTIONS),
)

def validate(root: Path | None = None):
    return validate_pack(
        script=SCRIPT,
        provider=PROVIDER,
        actions=ACTIONS,
        maintainer_only_shared_reference_names=MAINTAINER_ONLY_SHARED_REFERENCE_NAMES,
        utility_skills=UTILITY_SKILLS,
        curated_role_skills=CURATED_ROLE_SKILLS,
        root=root,
        enforce_reusable_instruction_boundaries=True,
    )


def main(argv: list[str] | None = None) -> int:
    return run_validator_cli(
        script=SCRIPT,
        provider=PROVIDER,
        actions=ACTIONS,
        maintainer_only_shared_reference_names=MAINTAINER_ONLY_SHARED_REFERENCE_NAMES,
        utility_skills=UTILITY_SKILLS,
        curated_role_skills=CURATED_ROLE_SKILLS,
        enforce_reusable_instruction_boundaries=True,
        argv=argv,
        description=__doc__,
    )


if __name__ == "__main__":
    raise SystemExit(main())
