#!/usr/bin/env python3
"""Native Python structural validator for the codex skill pack."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

SCRIPT = Path(__file__).absolute()
ENGINE_NAME = "skill_pack_validator_runtime.py"


def _load_validator_engine():
    candidates = [SCRIPT.parent / ENGINE_NAME]
    if len(SCRIPT.parents) > 4:
        source_root = SCRIPT.parents[4]
        expected_source = (
            source_root
            / "src.codex"
            / "skills"
            / "lead"
            / "scripts"
            / SCRIPT.name
        )
        if SCRIPT == expected_source.resolve():
            candidates.append(source_root / "scripts" / ENGINE_NAME)
    for candidate in candidates:
        candidate = candidate.resolve()
        if not candidate.is_file():
            continue
        spec = importlib.util.spec_from_file_location(
            "_orchestrarium_skill_pack_validator_runtime",
            candidate,
        )
        if spec is None or spec.loader is None:
            continue
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        return module
    raise RuntimeError("validator-engine-not-found")


_ENGINE = _load_validator_engine()
validate_pack = _ENGINE.validate_pack
run_validator_cli = _ENGINE.run_validator_cli

PROVIDER = 'codex'
MAINTAINER_ONLY_SHARED_REFERENCE_NAMES = frozenset({"cross-pack-reconciliation.md"})
UTILITY_SKILLS = frozenset(
    {"init-project", "external-brigade", "second-opinion", "review-changes", "review-loop", "design-panel"}
)
CURATED_ROLE_SKILLS = frozenset({"lead", "product-manager", "analyst", "architect", "planner"})

_DECLARED_ACTIONS = (('direct', 'file', '@AGENTS'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/operating-model.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/subagent-contracts.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/external-dispatch.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/init-project/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/init-project/agents/openai.yaml'),
 ('direct', 'file', '@ROOT/src.codex/skills/external-brigade/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/external-brigade/agents/openai.yaml'),
 ('direct', 'file', '@ROOT/src.codex/skills/consultant/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/second-opinion/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/review-loop/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/review-loop/agents/openai.yaml'),
 ('direct', 'file', '@ROOT/src.codex/skills/design-panel/SKILL.md'),
 ('direct', 'file', '@ROOT/src.codex/skills/design-panel/agents/openai.yaml'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/scripts/check-publication-safety.py'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/scripts/check-publication-safety.sh'),
 ('direct', 'file', '@ROOT/src.codex/skills/lead/scripts/validate-skill-pack.py'),
 ('direct', 'file', '@ROOT/scripts/skill_pack_validator_runtime.py'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP1',
  'design-panel skill carries invariant marker DP1'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP2',
  'design-panel skill carries invariant marker DP2'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP3',
  'design-panel skill carries invariant marker DP3'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP4',
  'design-panel skill carries invariant marker DP4'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP5',
  'design-panel skill carries invariant marker DP5'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP6',
  'design-panel skill carries invariant marker DP6'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP7',
  'design-panel skill carries invariant marker DP7'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'DP8',
  'design-panel skill carries invariant marker DP8'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'INPUT_ONLY',
  'design-panel skill carries the INPUT_ONLY candidate disposition marker'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'RETURN(lead)',
  'design-panel skill carries the RETURN(lead) ledger-gate marker'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'synthesis',
  'design-panel skill names the synthesis step'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'N=2',
  'design-panel skill carries the N=2 default quorum marker'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  'Design-panel and review-loop selection',
  'lead operating-model carries the design-panel/review-loop selection block'),
 ('check_h2_section_contains',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  '## Design-panel and review-loop selection',
  'skills/design-panel/',
  'lead operating-model design-panel selection block names the installed binding path'),
 ('check_h2_section_contains',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  '## Design-panel and review-loop selection',
  'independence at **generation**',
  'lead operating-model design-panel selection block states the generation side of the distinction'),
 ('check_h2_section_contains',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  '## Design-panel and review-loop selection',
  'independence at **verification**',
  'lead operating-model design-panel selection block states the verification side of the distinction'),
 ('direct', 'file', '@ROOT/src.codex/agents/default.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/worker.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/explorer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/analyst.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/planner.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/architect.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/architecture-reviewer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/algorithm-scientist.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/computational-scientist.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/security-engineer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/security-reviewer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/backend-engineer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/platform-engineer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/qa-engineer.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/knowledge-archivist.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/mechanical-scout.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/mechanical-worker.toml'),
 ('direct', 'file', '@ROOT/src.codex/agents/orchestrarium-role-manifest.json'),
 ('direct', 'file', '@ROOT/shared/role-routing-policy.v1.json'),
 ('direct', 'file', '@ROOT/src.codex/README.md'),
 ('direct', 'file', '@ROOT/docs/README.md'),
 ('direct', 'file', '@ROOT/docs/agents-mode-reference.md'),
 ('direct', 'file', '@ROOT/docs/provider-runtime-layouts.md'),
 ('direct', 'file', '@ROOT/shared/schemas/agent-runs.schema.json'),
 ('direct', 'file', '@ROOT/scripts/check-agent-run-ledger-contract.py'),
 ('direct', 'file', '@ROOT/scripts/agent-run-ledger.py'),
 ('direct', 'file', '@ROOT/scripts/agent-run-ledger.sh'),
 ('direct', 'file', '@ROOT/scripts/check-work-items-state.py'),
 ('direct', 'file', '@ROOT/scripts/check-work-items-state.sh'),
 ('direct', 'file', '@ROOT/scripts/validate-work-item-state.py'),
 ('direct', 'file', '@ROOT/scripts/validate-work-item-state.sh'),
 ('direct', 'file', '@ROOT/references-codex/README.md'),
 ('direct', 'file', '@ROOT/src.claude/README.md'),
 ('direct', 'file', '@ROOT/docs/external-worker-design.md'),
 ('direct', 'file', '@ROOT/references-claude/README.md'),
 ('direct', 'file', '@ROOT/shared/references/README.md'),
 ('direct', 'file', '@ROOT/shared/references/evidence-based-answer-pipeline.md'),
 ('direct', 'file', '@ROOT/shared/references/subagent-operating-model.md'),
 ('direct', 'file', '@ROOT/shared/references/workflow-strategy-comparison.md'),
 ('direct', 'file', '@ROOT/shared/references/repository-publication-safety.md'),
 ('direct', 'file', '@ROOT/shared/references/ru/evidence-based-answer-pipeline.md'),
 ('direct', 'file', '@ROOT/shared/references/ru/subagent-operating-model.md'),
 ('direct', 'file', '@ROOT/shared/references/ru/workflow-strategy-comparison.md'),
 ('direct', 'file', '@ROOT/shared/references/ru/repository-publication-safety.md'),
 ('direct', 'ru_policy', 'ru_policy'),
 ('check_pointer',
  '@ROOT/references-codex/evidence-based-answer-pipeline.md',
  '../shared/references/evidence-based-answer-pipeline.md'),
 ('check_pointer',
  '@ROOT/references-codex/subagent-operating-model.md',
  '../shared/references/subagent-operating-model.md'),
 ('check_pointer',
  '@ROOT/references-codex/workflow-strategy-comparison.md',
  '../shared/references/workflow-strategy-comparison.md'),
 ('check_pointer',
  '@ROOT/references-codex/repository-publication-safety.md',
  '../shared/references/repository-publication-safety.md'),
 ('check_pointer',
  '@ROOT/references-codex/ru/evidence-based-answer-pipeline.md',
  '../../shared/references/ru/evidence-based-answer-pipeline.md'),
 ('check_pointer',
  '@ROOT/references-codex/ru/subagent-operating-model.md',
  '../../shared/references/ru/subagent-operating-model.md'),
 ('check_pointer',
  '@ROOT/references-codex/ru/workflow-strategy-comparison.md',
  '../../shared/references/ru/workflow-strategy-comparison.md'),
 ('check_pointer',
  '@ROOT/references-codex/ru/repository-publication-safety.md',
  '../../shared/references/ru/repository-publication-safety.md'),
 ('check_pointer',
  '@ROOT/references-claude/evidence-based-answer-pipeline.md',
  '../shared/references/evidence-based-answer-pipeline.md'),
 ('check_pointer',
  '@ROOT/references-claude/ru/evidence-based-answer-pipeline.md',
  '../../shared/references/ru/evidence-based-answer-pipeline.md'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  "This file is the canonical shared core for the repository's subagent operating model.",
  'shared subagent-operating-model declares canonical shared-core ownership'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Keep runtime-specific paths, provider dispatch details, execution-model differences, and repository '
  'concretization in the corresponding pack-local addendum.',
  'shared subagent-operating-model keeps runtime specifics in pack-local addenda'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'and any pack-local provider-specific fields',
  'shared subagent-operating-model allows provider-specific addendum fields'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'A subagent `PASS`, report, or claimed test result is a claim, not proof',
  'shared subagent-operating-model requires subagent result verification'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Visual artifact verification amendment',
  'shared subagent-operating-model requires visual artifact inspection'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Documentation terminology amendment',
  'shared subagent-operating-model documents terminology glossary discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Markdown formula rendering amendment',
  'shared subagent-operating-model documents Markdown formula rendering discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'split long derivations into several short one-line',
  'shared subagent-operating-model preserves fragile previewer formula fallback'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'do not use multi-line `$$...$$` display blocks',
  'shared subagent-operating-model rejects unverified multi-line display math'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'compatibility hacks such as `\\sb` or `\\sp`',
  'shared subagent-operating-model forbids formula compatibility hacks'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'unbalanced dollar delimiters',
  'shared subagent-operating-model scans for delimiter and table breakage'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Formula scope and assumptions amendment',
  'shared subagent-operating-model documents formula scope discipline'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'tool availability',
  'shared subagent-operating-model preserves canonical-source ambiguity inspection'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'smallest safe reversible subset',
  'shared subagent-operating-model preserves user-intent fallback discipline'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '.agents/.agents-mode.yaml',
  'shared subagent-operating-model stays free of Codex-specific agents-mode paths'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '.claude/.agents-mode.yaml',
  'shared subagent-operating-model stays free of Claude-specific agents-mode paths'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'work-items/index.md',
  'shared subagent-operating-model stays free of Claude task-memory concretization'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'externalClaudeProfile',
  'shared subagent-operating-model stays free of provider-specific profile fields'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Claude CLI',
  'shared subagent-operating-model stays free of provider-specific dispatch destinations'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  'Codex CLI',
  'shared subagent-operating-model stays free of provider-specific dispatch origins'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'shared subagent-operating-model stays free of Codex addendum sections'),
 ('check_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## Claude-specific runtime notes',
  'shared subagent-operating-model stays free of Claude addendum sections'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 1. Main rule for the lead',
  'shared subagent-operating-model keeps the main-rule section in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 6. Role map',
  'shared subagent-operating-model keeps the role-map section in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 8. Gates: what each stage must prove',
  'shared subagent-operating-model keeps the gate model in the shared core'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'agent-runs.jsonl` is the machine-readable execution ledger',
  'shared subagent-operating-model documents the agent execution ledger'),
 ('check_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  'no accepted `PASS` without evidence',
  'shared subagent-operating-model rejects PASS without evidence'),
 ('check_h2_section_contains',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 3.10 Periodic controls',
  'Use the corresponding pack-local `periodic-control-matrix.md` named in the local addendum as the '
  'canonical cadence, owner, evidence, and fail-action matrix.',
  'shared periodic-controls section routes ownership back through the pack-local addendum'),
 ('check_h2_section_absent',
  '@ROOT/shared/references/subagent-operating-model.md',
  '## 3.10 Periodic controls',
  '[periodic-control-matrix.md](periodic-control-matrix.md)',
  'shared periodic-controls section does not keep a broken shared periodic-control link'),
 ('check_exact_h2_inventory',
  '@ROOT/shared/references/subagent-operating-model.md',
  'shared subagent-operating-model keeps the canonical shared-core H2 skeleton',
  '## 1. Main rule for the lead',
  '## 2. What this means in practice',
  '## 3. Team operating model',
  '## 3.10 Periodic controls',
  '## 4. Standard task template for any subagent',
  '## 5. Shared system preamble for all subagents',
  '## 6. Role map',
  '## 7. Ready-made role prompts',
  '## 8. Gates: what each stage must prove',
  '## 9. Practical routing patterns',
  '## 10. Rules for parallel work',
  '## 11. Governance notes',
  '## 12. Team composition',
  '## 13. Short memo for the lead',
  '## 14. Final wording to give the lead',
  '## Terms and Abbreviations'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'Consultant config lives in `.agents/.agents-mode.yaml`',
  'Codex runtime-notes section documents the Codex agents-mode path'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'externalClaudeProfile',
  'Codex runtime-notes section documents the Codex-only externalClaudeProfile field'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'Shipped production `auto` uses `codex | claude` only.',
  'Codex runtime-notes section documents profile-based Codex external dispatch'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'sequential skill invocation',
  'Codex runtime-notes section keeps the sequential-execution runtime note'),
 ('check_h2_section_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  '.claude/.agents-mode.yaml',
  'Codex runtime-notes section does not accidentally carry Claude agents-mode paths'),
 ('check_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-specific runtime notes',
  'Codex addendum keeps the Codex runtime-notes section'),
 ('check_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-side repository concretization',
  'Codex addendum keeps the Codex repository-concretization section'),
 ('check_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Shared core now owns',
  'Codex addendum keeps the shared-core ownership handoff section'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Codex-side repository concretization',
  '[periodic-control-matrix.md](periodic-control-matrix.md)',
  'Codex repository-concretization section keeps the pack-local periodic-control reference'),
 ('check_h2_section_contains',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## Shared core now owns',
  'Main rule, core management rules, delivery loops, routing patterns, role map, prompts, gates, and team '
  'composition',
  'Codex shared-core handoff section states which methodology stays in the shared core'),
 ('check_exact_h2_inventory',
  '@ROOT/references-codex/subagent-operating-model.md',
  'Codex addendum keeps the exact addendum-only H2 skeleton',
  '## Codex-specific runtime notes',
  '## Codex-side repository concretization',
  '## Shared core now owns'),
 ('check_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## 1. Main rule for the lead',
  'Codex addendum does not reintroduce the shared main-rule section'),
 ('check_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## 6. Role map',
  'Codex addendum does not reintroduce the shared role-map section'),
 ('check_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## 8. Gates: what each stage must prove',
  'Codex addendum does not reintroduce the shared gate section'),
 ('check_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## 9. Practical routing patterns',
  'Codex addendum does not reintroduce the shared routing-patterns section'),
 ('check_absent',
  '@ROOT/references-codex/subagent-operating-model.md',
  '## 12. Team composition',
  'Codex addendum does not reintroduce the shared team-composition section'),
 ('check_max_lines',
  '@ROOT/references-codex/subagent-operating-model.md',
  '120',
  'Codex addendum stays bounded instead of regrowing into a full blueprint copy'),
 ('check_normalized_sha256',
  '@ROOT/shared/references/subagent-operating-model.md',
  '1fccb602503eb700be3d6594b39a83c18e05caa13e9884aef86e96ffb2f21f84',
  'shared subagent-operating-model matches the current canonical normalized fingerprint'),
 ('check_normalized_sha256',
  '@ROOT/references-codex/subagent-operating-model.md',
  'fbd48b3063bb1b018928dc74107365aa7ad467f78650268a5352af4012946d03',
  'Codex addendum matches the current canonical normalized fingerprint'),
 ('direct', 'role_index_codex', 'role_index_codex'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/accessibility-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/accessibility-reviewer/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/algorithm-scientist/agents/openai.yaml',
  '@ROOT/src.codex/skills/algorithm-scientist/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/analyst/agents/openai.yaml',
  '@ROOT/src.codex/skills/analyst/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/analyzing-video-bugs/agents/openai.yaml',
  '@ROOT/src.codex/skills/analyzing-video-bugs/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/architect/agents/openai.yaml',
  '@ROOT/src.codex/skills/architect/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/architecture-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/architecture-reviewer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/backend-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/backend-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/bug-hunting/agents/openai.yaml',
  '@ROOT/src.codex/skills/bug-hunting/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/computational-scientist/agents/openai.yaml',
  '@ROOT/src.codex/skills/computational-scientist/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/data-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/data-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/design-panel/agents/openai.yaml',
  '@ROOT/src.codex/skills/design-panel/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/explain-simply/agents/openai.yaml',
  '@ROOT/src.codex/skills/explain-simply/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/external-brigade/agents/openai.yaml',
  '@ROOT/src.codex/skills/external-brigade/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/external-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/external-reviewer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/external-worker/agents/openai.yaml',
  '@ROOT/src.codex/skills/external-worker/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/frontend-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/frontend-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/geometry-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/geometry-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/graphics-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/graphics-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/knowledge-archivist/agents/openai.yaml',
  '@ROOT/src.codex/skills/knowledge-archivist/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/lead/agents/openai.yaml',
  '@ROOT/src.codex/skills/lead/agents/openai.yaml interface block parses with required keys (display_name, '
  'short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/manual-repo-transfer/agents/openai.yaml',
  '@ROOT/src.codex/skills/manual-repo-transfer/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/mathtype-book-page/agents/openai.yaml',
  '@ROOT/src.codex/skills/mathtype-book-page/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/model-view-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/model-view-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/performance-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/performance-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/performance-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/performance-reviewer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/planner/agents/openai.yaml',
  '@ROOT/src.codex/skills/planner/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/platform-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/platform-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/product-analyst/agents/openai.yaml',
  '@ROOT/src.codex/skills/product-analyst/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/product-manager/agents/openai.yaml',
  '@ROOT/src.codex/skills/product-manager/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/qa-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/qa-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/qt-ui-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/qt-ui-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/reliability-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/reliability-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/review-changes/agents/openai.yaml',
  '@ROOT/src.codex/skills/review-changes/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/review-loop/agents/openai.yaml',
  '@ROOT/src.codex/skills/review-loop/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/security-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/security-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/security-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/security-reviewer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/toolchain-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/toolchain-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/ui-test-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/ui-test-engineer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/ux-designer/agents/openai.yaml',
  '@ROOT/src.codex/skills/ux-designer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/ux-reviewer/agents/openai.yaml',
  '@ROOT/src.codex/skills/ux-reviewer/agents/openai.yaml interface block parses with required keys '
  '(display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/vak-dissertation-review/agents/openai.yaml',
  '@ROOT/src.codex/skills/vak-dissertation-review/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/visualization-engineer/agents/openai.yaml',
  '@ROOT/src.codex/skills/visualization-engineer/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_openai_yaml_interface',
  '@ROOT/src.codex/skills/windows-gui-manual-testing/agents/openai.yaml',
  '@ROOT/src.codex/skills/windows-gui-manual-testing/agents/openai.yaml interface block parses with required '
  'keys (display_name, short_description, default_prompt)'),
 ('check_skill_frontmatter_yaml',
  'accessibility-reviewer',
  'algorithm-scientist',
  'analyst',
  'analyzing-video-bugs',
  'architect',
  'architecture-reviewer',
  'backend-engineer',
  'bug-hunting',
  'computational-scientist',
  'consultant',
  'data-engineer',
  'design-panel',
  'explain-simply',
  'external-brigade',
  'external-reviewer',
  'external-worker',
  'frontend-engineer',
  'geometry-engineer',
  'graphics-engineer',
  'init-project',
  'knowledge-archivist',
  'lead',
  'manual-repo-transfer',
  'mathtype-book-page',
  'model-view-engineer',
  'performance-engineer',
  'performance-reviewer',
  'planner',
  'platform-engineer',
  'product-analyst',
  'product-manager',
  'qa-engineer',
  'qt-ui-engineer',
  'reliability-engineer',
  'review-changes',
  'review-loop',
  'second-opinion',
  'security-engineer',
  'security-reviewer',
  'toolchain-engineer',
  'ui-test-engineer',
  'ux-designer',
  'ux-reviewer',
  'vak-dissertation-review',
  'visualization-engineer',
  'windows-gui-manual-testing'),
 ('check_skill_description_budget',
  '460',
  '4000',
  'accessibility-reviewer',
  'algorithm-scientist',
  'analyst',
  'analyzing-video-bugs',
  'architect',
  'architecture-reviewer',
  'backend-engineer',
  'bug-hunting',
  'computational-scientist',
  'consultant',
  'data-engineer',
  'design-panel',
  'explain-simply',
  'external-brigade',
  'external-reviewer',
  'external-worker',
  'frontend-engineer',
  'geometry-engineer',
  'graphics-engineer',
  'init-project',
  'knowledge-archivist',
  'lead',
  'manual-repo-transfer',
  'mathtype-book-page',
  'model-view-engineer',
  'performance-engineer',
  'performance-reviewer',
  'planner',
  'platform-engineer',
  'product-analyst',
  'product-manager',
  'qa-engineer',
  'qt-ui-engineer',
  'reliability-engineer',
  'review-changes',
  'review-loop',
  'second-opinion',
  'security-engineer',
  'security-reviewer',
  'toolchain-engineer',
  'ui-test-engineer',
  'ux-designer',
  'ux-reviewer',
  'vak-dissertation-review',
  'visualization-engineer',
  'windows-gui-manual-testing'),
 ('direct', 'utility_design_panel', 'design-panel is registered in UTILITY_SKILLS'),
 ('direct', 'orphan_codex', 'orphan_codex'),
 ('check_common_skill_body_pin',
  'analyzing-video-bugs',
  'cf78ec0176f1726891045a2c2626363377994f34f081f9a9ad0ffbdb60740e91',
  '@ROOT/src.codex/skills/analyzing-video-bugs/SKILL.md'),
 ('check_common_skill_body_pin',
  'bug-hunting',
  '56c6ed8a5a590559bdf29409102b2b8b654bf73c7be2b4ef23c4d2c74e019232',
  '@ROOT/src.codex/skills/bug-hunting/SKILL.md'),
 ('check_common_skill_body_pin',
  'explain-simply',
  'f0f0e4dd1bed68aa8114adf6059fea32fedbee8fd06bf8bb12042dcd07ebb408',
  '@ROOT/src.codex/skills/explain-simply/SKILL.md'),
 ('check_common_skill_body_pin',
  'github-pr-review-bot',
  'c5be47bc165ad0e348cc708ab5d6196452505176074c0d84a36a520b564ad2e9',
  '@ROOT/src.codex/skills/github-pr-review-bot/SKILL.md'),
 ('check_common_skill_body_pin',
  'manual-repo-transfer',
  'a4d36b4123fb3b5461555da2fbd3615260483e6f67aed6cbeeb6704dc482d4ac',
  '@ROOT/src.codex/skills/manual-repo-transfer/SKILL.md'),
 ('check_common_skill_body_pin',
  'repo-cleanup',
  'e618521a08476c7ae31a03a2cba02a1b885d50fb0455bd7e765681b948502623',
  '@ROOT/src.codex/skills/repo-cleanup/SKILL.md'),
 ('check_common_skill_body_pin',
  'mathtype-book-page',
  '615499de68dc03fccb23954e8ed94662076a9a744a493b71232ebdcce55357be',
  '@ROOT/src.codex/skills/mathtype-book-page/SKILL.md'),
 ('check_common_skill_body_pin',
  'vak-dissertation-review',
  'e259d114a1ea2372d9152a07445aeba82c51493b9caf7b39f3b6b96678e9b261',
  '@ROOT/src.codex/skills/vak-dissertation-review/SKILL.md'),
 ('check_common_skill_body_pin',
  'windows-gui-manual-testing',
  'b3a029e6784d1d9e37f789b8b512f31f5e5c2161ca6807dc8a140854042ae6c8',
  '@ROOT/src.codex/skills/windows-gui-manual-testing/SKILL.md'),
 ('direct', 'common_pin_completeness', 'common_pin_completeness'),
 ('direct', 'layering_codex', 'layering_codex'),
 ('direct', 'scripts_codex', 'scripts_codex'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'consultantMode: auto',
  'consultant skill does not document consultantMode auto'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'fallback approved by user',
  'consultant skill does not reserve consultant fallback deviations'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md',
  'consultantMode: auto',
  'second-opinion skill does not expose consultantMode auto'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'allowed: external | auto | internal | disabled',
  'init-project skill restricts consultantMode to external/internal/disabled'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'allowed: external | auto | internal | disabled',
  'external-dispatch schema restricts consultantMode to external/internal/disabled'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'fallback approved by user',
  'external-dispatch does not record consultant fallback approvals'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'Read and normalize `.agents/.agents-mode.yaml` before trusting its flags.',
  'subagent-contracts require read-time agents-mode normalization'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'agent-runs.jsonl format',
  'subagent-contracts define the agent run ledger format'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'A `PASS` in `status.md` is not accepted',
  'subagent-contracts reject PASS without ledger evidence'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'shared/schemas/agent-runs.schema.json',
  'subagent-contracts point to the shared ledger schema'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'scripts/agent-run-ledger.*',
  'subagent-contracts point to the work-item ledger helper'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'scripts/validate-work-item-state.* --work-item',
  'subagent-contracts point to the work-item state validator'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'scripts/check-work-items-state.* --root',
  'subagent-contracts point to the periodic work-item state checker'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'Dead/superseded code disposition:',
  'subagent-contracts require a dead/superseded code disposition'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'Cleanup disposition:',
  'subagent-contracts require a cleanup disposition'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'For `Cleanup disposition`, `preserved` requires a reason and `none` means the recipient owns no resource in '
  'that category.',
  'subagent-contracts define cleanup disposition outcomes'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'report the Cleanup disposition for owned child process trees, temp/capture paths, and isolation worktrees as '
  '`cleaned`, `preserved` with its reason, or `none`',
  'subagent-contracts require the receiving-side cleanup echo'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'When a change supersedes a mechanism, `none` is invalid.',
  'subagent-contracts reject none for superseded mechanisms'),
 ('check_contains',
  '@ROOT/src.codex/skills/qa-engineer/SKILL.md',
  'cannot return `PASS` until it verifies the disposition field against the diff',
  'QA gate verifies dead/superseded code disposition before PASS'),
 ('check_contains',
  '@ROOT/src.codex/AGENTS.codex.md',
  'Before every native subagent spawn, the caller discovers the tools available at that moment and selects the exact task-scoped MCP/tool identifiers, or `none`.',
  'Codex AGENTS owns per-spawn exact tool discovery and selection'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'Populate `Allowed tools` under the caller-owned tool selection contract in installed `AGENTS.md`.',
  'subagent-contracts consume the canonical caller-owned tool selection contract'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'runtime default surface',
  'subagent-contracts forbid runtime default surface for native dispatch'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'caller-owned tool selection contract in the installed `AGENTS.md`',
  'lead points to the canonical caller-owned tool selection contract'),
 ('check_contains',
  '@ROOT/src.codex/skills/bug-hunting/SKILL.md',
  '**Second-cross-break stop:** If a second fix in the same session breaks a previously working neighbor, '
  'STOP all edits.',
  'bug-hunting skill carries the P4 second-cross-break stop rule'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/hooks/check-no-trash-in-repo.py',
  'REQUESTED_ISOLATION_MARKER = "# orchestrarium:requested-isolation-worktree"',
  'no-trash-in-repo hook carries the A2 requested-isolation-worktree marker constant'),
 ('check_contains',
  '@ROOT/src.codex/skills/review-loop/SKILL.md',
  '**Failed lane is unverified.** Any expected lane that errors, dies, or hits a time/token/usage limit is '
  'UNVERIFIED.',
  'review-loop skill carries the A5b failed-lane-is-unverified invariant'),
 ('check_contains',
  '@ROOT/src.codex/skills/review-loop/SKILL.md',
  '**Fail-closed aggregation.** A missing/null sub-verdict or findings payload is NOT-clean.',
  'review-loop skill carries the A5b fail-closed-aggregation invariant'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  '**Class-completeness trigger (mandatory):** when a reviewer, bot, or test cites one instance of a defect '
  'class',
  'subagent-contracts carry the A8 class-completeness trigger'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'Every provider-backed run MUST carry the resolved model/profile and effort as explicit launch flags in '
  'that invocation, even when they equal configured defaults; never rely on provider config defaults.',
  'external-dispatch carries the A12 explicit model/effort launch rule'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  'lifecycle state change (create, resume, stage transition, park, close, archive)',
  'operating-model carries the A3 physical-state reconciliation trigger'),
 ('check_contains',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'normalize it to the current canonical format before presenting or trusting the current values.',
  'init-project normalizes existing agents-mode before reading values'),
 ('check_contains',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'Any read of `.agents/.agents-mode.yaml` that drives a decision should normalize the file to the current '
  'canonical format before trusting the flags.',
  'init-project requires read-time agents-mode normalization'),
 ('check_contains',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md',
  'read and normalize `.agents/.agents-mode.yaml` first.',
  'second-opinion normalizes agents-mode before reporting status'),
 ('check_absent',
  '@AGENTS',
  'Adapter host runtime',
  'shared governance no longer allows adapter-host metadata for external execution'),
 ('check_contains',
  '@AGENTS',
  'must use direct external launch',
  'shared governance requires direct external launch'),
 ('check_contains',
  '@AGENTS',
  'substantive task prompt must use file-based prompt delivery',
  'shared governance requires file-based external CLI prompts'),
 ('check_contains',
  '@AGENTS',
  'Mechanism inventory before new paths',
  'shared governance requires owner inventory before new mechanisms'),
 ('check_contains',
  '@AGENTS',
  'State-synchronization ownership',
  'shared governance requires state synchronization ownership discipline'),
 ('check_contains',
  '@AGENTS',
  'split-brain state sync as an architecture bug',
  'shared governance rejects split-brain state synchronization'),
 ('check_contains',
  '@AGENTS',
  'correlation IDs',
  'shared governance requires traceable state synchronization diagnostics'),
 ('check_contains',
  '@AGENTS',
  'verify every subagent result before accepting it',
  'shared governance requires verification before trusting subagent results'),
 ('check_contains',
  '@AGENTS',
  'Visual artifact verification discipline',
  'shared governance requires visual inspection for generated visual artifacts'),
 ('check_contains',
  '@AGENTS',
  'Plain-language and terminology discipline',
  'shared governance requires terminology and abbreviation explanations in documents'),
 ('check_contains',
  '@AGENTS',
  'concrete observable data',
  'shared governance requires measured evidence before root-cause or fix claims'),
 ('check_contains',
  '@AGENTS',
  'smallest safe reversible subset',
  'shared governance preserves user-intent fallback discipline'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'Adapter host runtime:',
  'external-dispatch no longer records adapter host runtime'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'must use direct external launch',
  'external-dispatch requires direct external launch'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'approved thin wrapper',
  'external-dispatch requires approved wrapper prompts'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'file/stdin prompt delivery',
  'external-dispatch requires file/stdin prompt delivery'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'raw CLI, transport-neutral, inline, and caller-sidecar prompt chains are unsupported',
  'external-dispatch rejects raw and inline substantive prompts'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'Adapter host runtime:',
  'consultant no longer records adapter host runtime'),
 ('check_contains',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'must use direct external launch',
  'consultant requires direct external launch when external'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'Adapter host runtime:',
  'external-worker no longer records adapter host runtime'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'direct external launch contract',
  'external-worker requires direct external launch'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'file-based prompt delivery',
  'external-worker requires file-based external CLI prompts'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'Adapter host runtime:',
  'external-reviewer no longer records adapter host runtime'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'direct external launch contract',
  'external-reviewer requires direct external launch'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'file-based prompt delivery',
  'external-reviewer requires file-based external CLI prompts'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex dispatch owner cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex consultant cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex worker cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex reviewer cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/src.codex/skills/review-loop/SKILL.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex review loop cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/src.codex/skills/design-panel/SKILL.md',
  'approved thin wrapper',
  'external prompt consumer inventory: Codex design panel cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/docs/external-worker-design.md',
  'approved thin wrapper',
  'external prompt consumer inventory: worker design cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'approved thin wrapper',
  'external prompt consumer inventory: agents-mode reference cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/shared/references/spine/verification-and-decision-discipline.md',
  'approved thin wrapper',
  'external prompt consumer inventory: verification discipline cites the wrapper boundary'),
 ('check_contains',
  '@ROOT/shared/references/review-loop-methodology.md',
  'approved thin wrapper',
  'external prompt consumer inventory: review-loop methodology cites the wrapper boundary'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'Actual execution path:** <external CLI (provider name) | internal subagent',
  'consultant does not mislabel internal subagent as actual execution path'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md',
  'same-provider brigade items may run in parallel',
  'external-brigade documents same-provider parallel reuse'),
 ('check_contains',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md',
  'It does not cap how many same-provider brigade items may run in parallel',
  'external-brigade keeps opinion counts separate from concurrency'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  '$external-brigade',
  'lead skill mentions the external-brigade utility'),
 ('check_contains',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'the main session IS the lead',
  'lead skill declares the Lead role is held BY the main session'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'context: fork',
  'lead skill is not dispatched as a forked subagent (no context: fork)'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/lead/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/lead/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/lead/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/lead/external-dispatch.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/lead/external-dispatch.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/lead/external-dispatch.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/lead/operating-model.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/lead/operating-model.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/operating-model.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/lead/operating-model.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/lead/subagent-contracts.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/consultant/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/consultant/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/consultant/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/external-worker/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/external-worker/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-worker/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/external-worker/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/external-reviewer/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/external-brigade/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/second-opinion/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/init-project/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/init-project/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/init-project/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/graphics-engineer/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/visualization-engineer/SKILL.md removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/consultant/agents/openai.yaml removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/second-opinion/agents/openai.yaml removes retired externalGeminiWorkdirMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml',
  'gemini-crosscheck',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml removes retired gemini-crosscheck profile'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml',
  'externalGeminiFallbackMode',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml removes retired externalGeminiFallbackMode'),
 ('check_absent',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml',
  'externalGeminiWorkdirMode',
  '@ROOT/src.codex/skills/init-project/agents/openai.yaml removes retired externalGeminiWorkdirMode'),
 ('check_h2_section_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  '### `externalPriorityProfiles`',
  'gemini',
  'Codex shipped externalPriorityProfiles keep Gemini out of auto'),
 ('check_h2_section_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  '### `externalPriorityProfiles`',
  'qwen',
  'Codex shipped externalPriorityProfiles keep Qwen out of auto'),
 ('check_h2_section_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  '## Shared lane-priority matrix',
  'gemini',
  'Codex shared lane matrix keeps Gemini out of auto'),
 ('check_h2_section_absent',
  '@ROOT/src.codex/skills/lead/external-dispatch.md',
  '## Shared lane-priority matrix',
  'qwen',
  'Codex shared lane matrix keeps Qwen out of auto'),
 ('check_contains',
  '@ROOT/src.codex/AGENTS.codex.md',
  '$external-brigade',
  'Codex platform rules mention the external-brigade utility skill'),
 ('check_contains',
  '@ROOT/src.codex/AGENTS.codex.md',
  'auto | codex | claude | kimi | grok',
  'Codex platform rules document the current provider universe'),
 ('check_contains',
  '@ROOT/install.sh',
  '"$SCRIPT_DIR/install.py"',
  'root Bash launcher delegates to the Python owner'),
 ('check_absent',
  '@ROOT/install.py',
  'run_all_available',
  'root Python installer has no aggregate all-provider helper'),
 ('check_contains',
  '@ROOT/README.md',
  'Pressing Enter selects the default production install',
  'README documents the Codex/Claude default root install'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'Pressing Enter selects the default production install',
  'INSTALL.md documents the Codex/Claude default root install'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  '.agents-mode.yaml',
  'INSTALL.md default project result includes provider overlay files'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  '`power-mode` | hardest-task maximum result',
  'agents-mode reference documents power-mode preset'),
 ('check_contains',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  '`power-mode` (hardest-task maximum result)',
  'Codex init-project exposes power-mode preset'),
 ('check_contains',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'review.security: 2',
  'Codex init-project correctness-first/power-mode presets raise review.security'),
 ('check_contains',
  '@ROOT/src.codex/skills/init-project/SKILL.md',
  'review.ui-visual-correctness: 2',
  'Codex init-project correctness-first/power-mode presets raise review.ui-visual-correctness'),
 ('direct', 'agents_contract', 'agents-mode machine-readable contract matches docs and init preset surfaces'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  '## Canonical maintenance',
  'agents-mode reference defines canonical maintenance'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'Read-time normalization preserves the effective values of known keys',
  'agents-mode reference documents read-time normalization semantics'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'Substantive task prompts are file-based by default',
  'agents-mode reference documents file-based external CLI prompts'),
 ('check_contains',
  '@ROOT/docs/agents-mode-reference.md',
  'agent-runs.jsonl',
  'agents-mode reference documents ledger fan-out tracking'),
 ('check_contains',
  '@ROOT/docs/external-worker-design.md',
  'Work-item ledger rule',
  'external-worker design maps execution records to the ledger'),
 ('check_normalizer_rejects_removed_providers',
  'agents-mode normalizer rejects removed providers and keeps reserve last or absent in custom auto profiles'),
 ('check_file', '@ROOT/shared/agents-mode.defaults.yaml', 'shared/agents-mode.defaults.yaml'),
 ('check_shared_defaults_reserve_policy', 'shared agents-mode defaults keep reserve advisory/review-only'),
 ('check_not_exists',
  '@ROOT/src.codex/agents-mode.defaults.yaml',
  'src.codex/agents-mode.defaults.yaml removed from the monorepo'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'Codex installs create only absent native role TOMLs',
  'INSTALL.md documents create-only native role installation'),
 ('check_contains',
  '@ROOT/docs/provider-runtime-layouts.md',
  'Native role manifest',
  'provider runtime layouts document the global native role manifest'),
 ('check_contains',
  '@ROOT/src.codex/README.md',
  'create-only native role payloads',
  'src.codex/README.md documents the native role install payload'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/validate-work-item-state.* --work-item',
  'README documents the work-item state validator'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/agent-run-ledger.* --work-item',
  'README documents the work-item ledger helper'),
 ('check_contains',
  '@ROOT/README.md',
  'scripts/check-work-items-state.* --root',
  'README documents the periodic work-item state checker'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'agent-runs.jsonl',
  'INSTALL documents local work-item execution tracking'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'scripts/agent-run-ledger.* --work-item',
  'INSTALL documents the work-item ledger helper'),
 ('check_contains',
  '@ROOT/INSTALL.md',
  'scripts/check-work-items-state.* --root',
  'INSTALL documents the periodic work-item state checker'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'machine-readable work-item execution tracking contract',
  'release notes document the work-item execution tracking contract'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'ledger append/init helper',
  'release notes document the ledger append/init helper'),
 ('check_contains',
  '@ROOT/RELEASE_NOTES.md',
  'periodic active work-item state checker',
  'release notes document the periodic work-item checker'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.py',
  'validate_work_item',
  'agent-run-ledger helper reuses the work-item state validator'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.py',
  'restore_ledger',
  'agent-run-ledger helper rolls back invalid appends'),
 ('check_contains',
  '@ROOT/scripts/agent-run-ledger.sh',
  'agent-run-ledger.py',
  'agent-run-ledger Bash wrapper targets the Python helper'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.py',
  'validate_work_item',
  'periodic work-item checker reuses the work-item state validator'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.py',
  'stale running agent',
  'periodic work-item checker reports stale running agents'),
 ('check_contains',
  '@ROOT/scripts/check-work-items-state.sh',
  'check-work-items-state.py',
  'periodic work-item Bash wrapper targets the Python checker'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'PASS gate requires evidence',
  'work-item state validator enforces evidence for PASS'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'escapes the work item',
  'work-item state validator confines PASS artifacts to the work item'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.py',
  'agent-runs.jsonl',
  'work-item state validator loads the agent run ledger'),
 ('check_contains',
  '@ROOT/scripts/validate-work-item-state.sh',
  'validate-work-item-state.py',
  'work-item state Bash wrapper targets the Python validator'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  'agent-runs.schema.json',
  'agent run ledger schema has a stable id'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  '"executionRole"',
  'agent run ledger schema defines executionRole'),
 ('check_contains',
  '@ROOT/shared/schemas/agent-runs.schema.json',
  '"evidence"',
  'agent run ledger schema defines evidence'),
 ('check_agent_run_ledger_contract', 'agent run ledger schema and validator reject schema-invalid events'),
 ('check_arch_layering_slices',
  'architecture-layering slices consistent across roles and claude/codex packs'),
 ('direct', 'codex_line_budget', 'Codex AGENTS.md pack section line budget <= 420 (420)'),
 ('direct', 'agents_heading', "Section '## Role index' present in AGENTS.md"),
 ('direct', 'agents_heading', "Section '## Engineering hygiene' present in AGENTS.md"),
 ('direct', 'agents_heading', "Section '## Publication safety' present in AGENTS.md"),
 ('direct', 'agents_heading', "Section '## Core delegation principles' present in AGENTS.md"),
 ('check_contains',
  '@AGENTS',
  "clarification that changes a live textual artifact's meaning supersedes its prior wording",
  'shared governance replaces meaning-changing textual clarifications instead of layering prose'))

_INSTALLED_ACTIONS = (
    (
        "check_normalized_sha256",
        "@PACK/contracts/ui-transition-continuity.md",
        "92af857398c6c56ff681fa91360673d7a9c2365f48734f6d83fa74d98e12cf62",
        "UI-CONTINUITY-CONTRACT-DRIFT: installed neutral contract leaf matches the canonical English fingerprint",
    ),
    ("check_file", "@SCRIPTS/agent-run-ledger.py", "installed agent-run-ledger.py"),
    ("check_file", "@SCRIPTS/agent-run-ledger.sh", "installed agent-run-ledger.sh"),
    ("check_file", "@SCRIPTS/review_loop_state.py", "installed review-loop state engine"),
    (
        "check_file",
        "@SCRIPTS/check-work-items-state.py",
        "installed check-work-items-state.py",
    ),
    (
        "check_file",
        "@SCRIPTS/check-work-items-state.sh",
        "installed check-work-items-state.sh",
    ),
    (
        "check_file",
        "@SCRIPTS/validate-work-item-state.py",
        "installed validate-work-item-state.py",
    ),
    (
        "check_file",
        "@SCRIPTS/validate-work-item-state.sh",
        "installed validate-work-item-state.sh",
    ),
    (
        "check_contains",
        "@SCRIPTS/agent-run-ledger.py",
        "validate_work_item",
        "installed agent-run-ledger helper reuses the validator",
    ),
    (
        "check_contains",
        "@SCRIPTS/check-work-items-state.py",
        "stale running agent",
        "installed periodic work-item checker reports stale running agents",
    ),
    (
        "check_contains",
        "@SCRIPTS/validate-work-item-state.py",
        "PASS gate requires evidence",
        "installed work-item state validator enforces evidence for PASS",
    ),
    (
        "check_contains",
        "@SCRIPTS/../shared/schemas/agent-runs.schema.json",
        "agent-runs.schema.json",
        "installed agent run ledger schema has a stable id",
    ),
    (
        "check_contains",
        "@SCRIPTS/../shared/schemas/agent-runs.schema.json",
        '"executionRole"',
        "installed agent run ledger schema defines executionRole",
    ),
    (
        "check_contains",
        "@SCRIPTS/../shared/schemas/agent-runs.schema.json",
        '"evidence"',
        "installed agent run ledger schema defines evidence",
    ),
    ("direct", "codex_native_override", "default.toml"),
    ("direct", "codex_native_override", "worker.toml"),
    ("direct", "codex_native_override", "explorer.toml"),
)

_APAT_ACTIONS = (
    ("check_file", "@SKILLS/lead/SKILL.md", "APAT-E006-INSTALLED-MISSING: codex lead APAT projection file"),
    ("check_file", "@SKILLS/architect/SKILL.md", "APAT-E006-INSTALLED-MISSING: codex architect AP0-AP5 projection file"),
    ("check_file", "@SKILLS/architecture-reviewer/SKILL.md", "APAT-E006-INSTALLED-MISSING: codex architecture-reviewer APAT projection file"),
    ("check_contains", "@SKILLS/lead/SKILL.md", "<!-- APAT-BLOCK:LEAD-ROUTING:BEGIN -->", "APAT-E006-INSTALLED-MISSING: codex lead APAT-G04-PROVIDER-PARITY projection marker"),
    ("check_contains", "@SKILLS/lead/SKILL.md", "is not a universal Architect prelude", "APAT-E006-INSTALLED-MISSING: codex lead APAT-G05-INSTALLED-PARITY negative-selection wording"),
    *(("check_contains", "@SKILLS/architect/SKILL.md", f'<!-- APAT-SEMANTIC id="AP{number}.', f"APAT-E006-INSTALLED-MISSING: codex architect AP{number} marker") for number in range(6)),
    ("check_contains", "@SKILLS/architect/SKILL.md", "<!-- APAT-BLOCK:ARCHITECT-DISPOSITION:BEGIN -->", "APAT-E006-INSTALLED-MISSING: codex architect AP0-AP5 projection section marker"),
    ("check_contains", "@SKILLS/architecture-reviewer/SKILL.md", "<!-- APAT-BLOCK:ARCHITECTURE-REVIEW:BEGIN -->", "APAT-E006-INSTALLED-MISSING: codex architecture-reviewer APAT projection section marker"),
    ("check_contains", "@SKILLS/architecture-reviewer/SKILL.md", "each tempting but unsuitable pattern has explicit negative evidence", "APAT-E006-INSTALLED-MISSING: codex architecture-reviewer APAT negative-selection wording"),
)

_APAT_DEV_ACTIONS = (
    ("check_file", "@ROOT/shared/references/architecture-pattern-applicability.md", "APAT-G04-PROVIDER-PARITY canonical applicability reference"),
    ("check_file", "@ROOT/shared/references/ru/architecture-pattern-applicability.md", "APAT-G04-PROVIDER-PARITY Russian applicability reference"),
)

_UI_CONTINUITY_DEV_ACTIONS = (
    (
        "check_normalized_sha256",
        "@ROOT/shared/references/ui-transition-continuity.md",
        "92af857398c6c56ff681fa91360673d7a9c2365f48734f6d83fa74d98e12cf62",
        "UI-CONTINUITY-CONTRACT-DRIFT: canonical English contract matches its declared fingerprint",
    ),
    (
        "check_contains",
        "@ROOT/scripts/production_installer.py",
        "UI_CONTINUITY_CONTRACT_SOURCE",
        "UI-CONTINUITY-CONTRACT-DRIFT: production installer declares the canonical contract source",
    ),
    (
        "check_contains",
        "@ROOT/scripts/production_installer.py",
        "UI_CONTINUITY_CONTRACT_TARGET",
        "UI-CONTINUITY-CONTRACT-DRIFT: production installer declares the neutral contract target",
    ),
    (
        "check_not_exists",
        "@ROOT/src.codex/contracts",
        "UI-CONTINUITY-CONTRACT-DRIFT: Codex has no provider-local contract copy",
    ),
    (
        "check_not_exists",
        "@ROOT/src.claude/contracts",
        "UI-CONTINUITY-CONTRACT-DRIFT: Claude has no provider-local contract copy",
    ),
)

_CODEX_HOOK_HEALTH_DEV_ACTIONS = (
    (
        "check_normalized_sha256",
        "@ROOT/scripts/check-hook-health.py",
        "381e7352e3eac59c8737414581758c3f038f04076ec29afb8c7adda916f7b8f5",
        "CODEX-HOOK-HEALTH-SIDECAR-DRIFT: root helper source matches its pinned payload",
    ),
)

_SOURCE_ONLY_MAINTAINER_PREFIXES = (
    "@ROOT/README.md",
    "@ROOT/shared/schemas/agent-runs.schema.json",
    "@ROOT/shared/references/",
    "@ROOT/shared/agents-mode.defaults.yaml",
    "@ROOT/docs/",
    "@ROOT/references-",
    "@ROOT/install.",
    "@ROOT/INSTALL.md",
    "@ROOT/RELEASE_NOTES.md",
    "@ROOT/scripts/agent-run-ledger",
    "@ROOT/scripts/validate-work-item-state",
)

_SOURCE_ONLY_MAINTAINER_OPERATIONS = (
    "check_normalizer_rejects_removed_providers",
    "check_shared_defaults_reserve_policy",
)


def _is_source_only_maintainer_action(action: tuple[str, ...]) -> bool:
    return (
        action[0] in _SOURCE_ONLY_MAINTAINER_OPERATIONS
        or any(
            str(value).startswith(_SOURCE_ONLY_MAINTAINER_PREFIXES)
            for value in action
        )
    )


# Historical sections retain their existing source coverage, but a source-only
# assertion may never leak into the installed-pack action set as an index moves.
_ALL_ACTIONS = (
    _DECLARED_ACTIONS[0:35]
    + _DECLARED_ACTIONS[142:304]
    + _DECLARED_ACTIONS[322:329]
    # Include declaration 372 so its @ROOT/docs prefix routes it to dev_repo.
    + _DECLARED_ACTIONS[366:373]
    + _APAT_ACTIONS
)

ACTIONS = (
    (
        "all",
        tuple(
            action for action in _ALL_ACTIONS
            if not _is_source_only_maintainer_action(action)
        ),
    ),
    (
        "dev_repo",
        _DECLARED_ACTIONS[35:51]
        + _DECLARED_ACTIONS[58:76]
        + _DECLARED_ACTIONS[86:122]
        + _DECLARED_ACTIONS[129:142]
        + _DECLARED_ACTIONS[318:321]
        + _DECLARED_ACTIONS[329:334]
        + _DECLARED_ACTIONS[335:342]
        + _DECLARED_ACTIONS[351:366]
        + tuple(
            action for action in _ALL_ACTIONS
            if _is_source_only_maintainer_action(action)
        )
        + _APAT_DEV_ACTIONS
        + _UI_CONTINUITY_DEV_ACTIONS
        + _CODEX_HOOK_HEALTH_DEV_ACTIONS,
    ),
    (
        "dev_repo_nonstandalone",
        _DECLARED_ACTIONS[51:58]
        + _DECLARED_ACTIONS[76:86]
        + _DECLARED_ACTIONS[122:129]
        + _DECLARED_ACTIONS[304:318]
        + _DECLARED_ACTIONS[321:322]
        + _DECLARED_ACTIONS[334:335]
        + _DECLARED_ACTIONS[342:351],
    ),
    ("installed", _INSTALLED_ACTIONS),
)

def validate(root: Path | None = None):
    return validate_pack(
        script=SCRIPT,
        provider=PROVIDER,
        actions=ACTIONS,
        maintainer_only_shared_reference_names=MAINTAINER_ONLY_SHARED_REFERENCE_NAMES,
        utility_skills=UTILITY_SKILLS,
        curated_role_skills=CURATED_ROLE_SKILLS,
        root=root,
        enforce_reusable_instruction_boundaries=True,
    )


def main(argv: list[str] | None = None) -> int:
    return run_validator_cli(
        script=SCRIPT,
        provider=PROVIDER,
        actions=ACTIONS,
        maintainer_only_shared_reference_names=MAINTAINER_ONLY_SHARED_REFERENCE_NAMES,
        utility_skills=UTILITY_SKILLS,
        curated_role_skills=CURATED_ROLE_SKILLS,
        enforce_reusable_instruction_boundaries=True,
        argv=argv,
        description=__doc__,
    )


if __name__ == "__main__":
    raise SystemExit(main())
